# Generated by Django 4.2.1 on 2023-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft', models.CharField(default='', max_length=100)),
                ('hard', models.CharField(default='', max_length=100)),
                ('boot', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(default='', max_length=100)),
                ('solution', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
